force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Primary_Objective__c.field-meta.xml
<CustomField>
    <fullName>Primary_Objective__c</fullName>
    <label>Primary Objective</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Risk Reduction</fullName>
            </value>
            <value>
                <fullName>Production Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewProjectCreationController.cls
public with sharing class NewProjectCreationController {
    @AuraEnabled(Cacheable = true)
    public static List<PicklistOption> getPrimaryObjectiveFieldValues() {
        List<PicklistOption> options = new List<PicklistOption>();

        Schema.DescribeFieldResult fieldResult = Project__c.Primary_Objective__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new PicklistOption(f.getLabel(), f.getValue()));
        }

        return options;
    }

    public class PicklistOption {
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}

        public PicklistOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}