force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/Channel_Post__c.object-meta.xml
<CustomObject>
    <label>Channel Post</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Channel Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Channel_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChannelPostService.cls
public with sharing class ChannelPostService {
    public void notifySubscribers(List<Channel_Post__c> posts) {
        Set<Id> channelIds = new Set<Id>();
        for (Channel_Post__c post : posts) {
            channelIds.add(post.Channel__c);
        }

        List<Subscription__c> subscriptions = [SELECT User__c FROM Subscription__c WHERE Channel__c IN :channelIds];

        Set<String> userIds = new Set<String>();
        for (Subscription__c subscription : subscriptions) {
            userIds.add(subscription.User__c);
        }

        String message = 'A new post arrived in your subscriptions. Review your followed items.';
        NotificationManager.notifyChannelSubscribers(userIds, message);
    }
}