force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/Channel_Post__c.object-meta.xml
<CustomObject>
    <label>Channel Post</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Channel Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Channel_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeedItemsService.cls
public with sharing class FeedItemsService {
    public List<Channel_Post__c> getChannelPostsLinkedToRunningUser() {
        return [
                SELECT Channel__r.Name, Message__c
                FROM Channel_Post__c
                WHERE Channel__c IN (SELECT Channel__c FROM Subscription__c WHERE User__c = :UserInfo.getUserId())
                ORDER BY CreatedDate DESC
        ];
    }

    public List<Channel_Post__c> getChannelPostsByChannelId(Id channelId) {
        return [
                SELECT Channel__r.Name, Message__c
                FROM Channel_Post__c
                WHERE Channel__c = :channelId
                ORDER BY CreatedDate DESC
        ];
    }

    public Channel_Post__c getChannelPostsById(Id itemId) {
        return [
                SELECT Channel__r.Name, Message__c
                FROM Channel_Post__c
                WHERE Id = :itemId
                LIMIT 1
        ];
    }
}