force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/Channel_Post__c.object-meta.xml
<CustomObject>
    <label>Channel Post</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Channel Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Post__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Channel_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChannelController.cls
public with sharing class ChannelController {
    @AuraEnabled(Cacheable = true)
    public static List<ItemWrapper> getFeedItems(Id channelId) {
        List<ItemWrapper> result = new List<ItemWrapper>();

        for (Channel_Post__c post : new FeedItemsService().getChannelPostsByChannelId(channelId)) {
            result.add(new ItemWrapper(post.Channel__r.Name, post.Message__c));
        }

        return result;
    }

    public class ItemWrapper {
        @AuraEnabled
        public String channelName { get; set; }
        @AuraEnabled
        public String message { get; set; }

        public ItemWrapper(String channelName, String message) {
            this.channelName = channelName;
            this.message = message;
        }
    }
}